services:
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
  springboot:
    image: ${DOCKER_IMAGE}:latest
    container_name: springboot
    depends_on:
      - redis
    build:
      context: src/main/java
      dockerfile: ./Dockerfile-dev
    ports:
      - 8080:8080
    env_file:
      - ./src/main/resources/application-secrets.properties
