services:
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
  springboot:
    env_file:
    - /home/ubuntu/application-secrets.properties
    image: ${DOCKER_IMAGE}
    container_name: springboot
    depends_on:
      - redis
    ports:
      - 8080:8080
