version: "3"
services:
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - wascomposenet
networks:
  wascomposenet:
    external: true


