spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_ENDPOINT_URL_DEV}:3306/${DATABASE_NAME_DEV}
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL_DEV}

sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  traces-sample-rate: 1.0
  enable-tracing: true
  exception-resolver-order: -2147483647
