spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:tcp://localhost/~/offroad
    username: sa
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL_DEV}

google:
  client-id: ${GOOGLE_CLIENT_ID_DEV}
  client-secret: ${GOOGLE_CLIENT_SECRET_DEV}
  redirect-url: ${GOOGLE_REDIRECT_URL_DEV}

jwt:
  secret: ${JWT_SECRET_DEV}

redis:
  host: localhost
  port: ${REDIS_PORT_DEV}

apple:
  auth:
    token-url: https://appleid.apple.com/auth/token
    public-key-url: https://appleid.apple.com/auth/keys
  redirect-uri: ${APPLE_REDIRECT_URL}
  iss: https://appleid.apple.com
  aud: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key:
    id: ${APPLE_KEY_ID}
    path: classpath:/apple/AuthKey_${APPLE_KEY_ID}.p8