spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://offroad.cvoamy0mckur.ap-northeast-2.rds.amazonaws.com:3306/offroad
    username: offroadserver
    password: dhvmfhem1**
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true