spring:
  config:
    import: application-secret.properties
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/offroad
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL_DEV}

google:
  client-id: ${GOOGLE_CLIENT_ID_DEV}
  client-secret: ${GOOGLE_CLIENT_SECRET_DEV}
  redirect-url: ${GOOGLE_REDIRECT_URL_DEV}

jwt:
  secret: ${JWT_SECRET_DEV}

redis:
  host: localhost
  port: ${REDIS_PORT_DEV}

apple:
  public-key-url: ${APPLE_PUBLIC_KEY_URL}
  iss: ${APPLE_ISS}
  client-id: ${APPLE_CLIENT_ID}

aws-property:
  s3-bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key: ${AWS_S3_ACCESS_KEY}
  secret-key: ${AWS_S3_SECRET_KEY}
  aws-region: ap-northeast-2

logging:
  level:
    root: info