package site.offload.enums.response;

public enum CustomErrorCode {
    CUSTOM_ERROR_CODE, // 예시 코드
    FAIL_REISSUE_TOKEN,
    NOT_EXISTS_MEMBER, // 존재하지 않는 유저
    NOT_EXISTS_PLACE_CATEGORY, // 존재하지 않은 장소 카테고리
    NOT_EXISTS_CHARACTER, // 존재하지 않는 캐릭터
    NOT_EXISTS_CHARACTER_MOTION, // 존재하지 않는 캐릭터 모션
    NOT_EXISTS_EMBLEM,
    NOT_EXISTS_PLACE,
    NOT_EXISTS_PROCEEDING_QUEST,
    NOT_EXISTS_EMBLEM_CODE,
    NOT_EXISTS_QUEST,
    NOT_EXISTS_COUPON,
    NOT_EXISTS_QUEST_REWARD,
    NOT_EXISTS_GAINED_COUPON,
    INVALID_AUTHORIZATION_JWT,
    INVALID_EXPIRATION_JWT,
    INVALID_MEMBER_DELETE_CODE,
    INVALID_MEMBER_STATUS,
    TOO_FAR_DISTANCE,
    INVALID_AUTHORIZATION_FILTER,
    FAIL_EMBLEM_UPDATE,
    NOT_GAINED_CHARACTER;
}
