name: CI

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: create application-secret.properties
        run: |
          ## create application-secret.properties
          mkdir -p ./offroad-api/src/main/resources
          cd ./offroad-api/src/main/resources

          # application-secret.properties 파일 생성
          touch ./application-secret.properties

          # GitHub-Actions 에서 설정한 값을 application-secret.properties 파일에 쓰기
          echo "${{ secrets.PROPERTIES_APPLICATION }}" > ./application-secret.properties

      - name: create application.yml
        run: |
          ## create application-dev.yml
          cd ./offroad-api/src/main/resources
          
          # application-dev.yml 파일 생성
          touch ./application-dev.yml 
          
          # GitHub-Actions 에서 설정한 값을 application-dev.yml 파일에 쓰기
          echo "${{ secrets.CI_APPLICATION_DEV }}" > ./application-dev.yml

        shell: bash

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew :offroad-api:build -x test
        shell: bash